### Register
POST http://localhost:3000/signup
content-type: application/json

{
  "email": "pipo@pipo.fr",
  "password": "test",
  "first_name": "Jean-Claude",
  "last_name":"Dus",
  "role": "public"
}

### Login 
POST http://localhost:3000/login
content-type: application/json

{
  "email": "pipo@pipo.fr",
  "password": "test"
}

### Get Users
GET http://localhost:3000/users

### Get User by Id
GET http://localhost:3000/user/4


### Update user by Id
PUT http://localhost:3000/user/update/1
content-type: application/json

{
  "first_name": "Jean",
  "last_name": "Dujardin"
}

### Update user password by Id
PUT http://localhost:3000/user/update/1
content-type: application/json

{
  "password": "1234"
}

### Delete User by User Id
DELETE http://localhost:3000/user/delete/3


### Get Beds
GET http://localhost:3000/beds

### Get Bed by user Id
GET http://localhost:3000/bed/user/2

### Create Bed
POST http://localhost:3000/bed/create
content-type: application/json

{
    "num":45,
    "floor":1,
    "availability":true,
    "occupancy_time":0
}

### Get free bed by floor
GET http://localhost:3000/bed/floor/2

### Assign bed to user
POST http://localhost:3000/bed/assign
content-type: application/json

{
  "bedId": 4,
  "userId": 2,
  "occupancy_time": 10
}

### Unassign Bed to user
POST http://localhost:3000/bed/unassign
content-type: application/json

{
"bedId": 4
}